### ISSUE TITLE
integration 'plugwise_stick' does not have a valid version key

### ISSUE THREAD

**Issue by sj3fk3** [brefra/home-assistant-plugwise-stick#11]
Maybe only fix this so we can still use this integration?

The custom integration 'plugwise_stick' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.ho
me-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

**Comment by brefra** [comment]
I've just added version key in release 2.0.2
