### ISSUE TITLE
configuration not available

### ISSUE THREAD

**Issue by supermarcie** [brefra/home-assistant-plugwise-stick#7]
I don't find the configuration where to enter the path to the USB stick.
Were can I configure this?

**Comment by Ghannes** [comment]
![image](https://user-images.githubusercontent.com/2785175/97812429-9456af80-1c81-11eb-8b49-d0cccfb663d4.png)
you need to add the integration. When you click 'Plugwise USB stick' it will popup
![image](https://user-images.githubusercontent.com/2785175/97812450-b0f2e780-1c81-11eb-94df-57b6579ad171.png)

**Comment by supermarcie** [comment]
ok found it, thanks for the support, it is working fine now.
