### ISSUE TITLE
Plugwise stick not showing up in integrations

### ISSUE THREAD

**Issue by HansMolenveld** [brefra/home-assistant-plugwise-stick#9]
I did install the repository through HACS. Than I restarted HA. Did this several times but not showing up. I don't even get the warning about using a hacs integration plugwise stick. I did then start HA again and the log on debug. Then I See the line of the warning:
[homeassistant.loader] You are using a custom integration for plugwise_stick which has not been tested by Home Assistant.
Also get this:
(SyncWorker_1) [homeassistant.util.json] JSON file not found: /config/custom_components/plugwise_stick/translations/nl.json
Further there is nothing in the logging no error messages.
I am running HA in docker on an raspberrypi 3b+.
What could be the problem?
[ha_debug.log](https://github.com/brefra/home-assistant-plugwise-stick/files/5506598/ha_debug.log)

**Comment by Ghannes** [comment]
Hi Hans, Did you have a look at the closed issues? Seems like this was already reported (and fixed).

Thanks,
Hans

**Comment by HansMolenveld** [comment]
Thank you for replying. I did look at the closed issue's and I thought this was a solution but it is not. The plugwise stick doesn't appear in de the integrations when I tick on plus. HA is restarted now 10 times or so. I have put some printscreens.
![Logbook](https://user-images.githubusercontent.com/35487936/98482474-f1161500-2201-11eb-943b-2b0496b43c73.PNG)
![hacs_install](https://user-images.githubusercontent.com/35487936/98482475-f1aeab80-2201-11eb-9b8a-12af92f91e50.PNG)
![Integratie](https://user-images.githubusercontent.com/35487936/98482476-f2474200-2201-11eb-8196-c7790c895e93.PNG)

**Comment by brefra** [comment]
Hello Hans,  it looks like a translation file issue. As a workarround you could copy the `/config/custom_components/plugwise_stick/translations/en.json` file to `/config/custom_components/plugwise_stick/translations/nl.json`

Please be aware I'm planning to retire this specific custom integration in the near future as I joined the [plugwise](https://github.com/plugwise) team. Together we are currently in the process of transfering the functionality of this integration into the "out-of-the-box" Plugwise integration within Home Assistant.
In the meanwhile you could use the [plugwise-beta](https://github.com/plugwise/plugwise-beta) version, which has the support for the USB stick already.

**Comment by HansMolenveld** [comment]
Thank you this was the trick. I have now the usb stick available and also have the circles in my HA. I am looking forward to the new integration thank you.
